return {
	template = "\n\nvoid gp_lsp_probe() {\n  \n}",
	affixes = {
		Class = { { prefix = "  (*", suffix = "). " }, { prefix = "  ", suffix = ". " } },
		Variable = { { prefix = "  (*", suffix = "). " }, { prefix = "  ", suffix = ". " } },
		Struct = { { prefix = "  (*", suffix = "). " }, { prefix = "  ", suffix = ". " } },
		Module = { { prefix = "  ", suffix = ". " } },
		Interface = { { prefix = "  ", suffix = ". " } },
		Field = { { prefix = "  ", suffix = ". " } },
	},
	no_complete = {},
	ignore = {
		Function = {
			["gp_lsp_probe()"] = "void",
		},
		Keyword = {
			_Bool = {},
			_Complex = {},
			_Imaginary = {},
			_Nonnull = {},
			_Null_unspecified = {},
			_Nullable = {},
			__FUNCTION__ = {},
			__PRETTY_FUNCTION__ = {},
			__auto_type = {},
			__func__ = {},
			char = {},
			const = {},
			double = {},
			enum = {},
			extern = {},
			float = {},
			int = {},
			long = {},
			restrict = {},
			short = {},
			signed = {},
			static = {},
			struct = {},
			union = {},
			unsigned = {},
			void = {},
			volatile = {},
		},
	},
}
