return {
	template = "\n\nvoid gp_lsp_probe() {\n  \n}",
	affixes = {
		Class = {
			{ prefix = "  ", suffix = ":: " },
			{ prefix = "  ", suffix = "-> " },
			{ prefix = "  ", suffix = ". " },
		},
		Variable = {
			{ prefix = "  ", suffix = ":: " },
			{ prefix = "  ", suffix = "-> " },
			{ prefix = "  ", suffix = ". " },
		},
		Struct = {
			{ prefix = "  ", suffix = ":: " },
			{ prefix = "  ", suffix = "-> " },
			{ prefix = "  ", suffix = ". " },
		},
		Module = {
			{ prefix = "  ", suffix = ":: " },
			{ prefix = "  ", suffix = "-> " },
			{ prefix = "  ", suffix = ". " },
		},
		Interface = {
			{ prefix = "  ", suffix = ":: " },
			{ prefix = "  ", suffix = "-> " },
			{ prefix = "  ", suffix = ". " },
		},
		Field = {
			{ prefix = "  ", suffix = ":: " },
			{ prefix = "  ", suffix = "-> " },
			{ prefix = "  ", suffix = ". " },
		},
	},
	no_complete = {},
	ignore = {
		Function = {
			["gp_lsp_probe()"] = "void",
		},
		Interface = {
			Class = {},
			FILE = {},
			SEL = {},
			femode_t = {},
			fenv_t = {},
			fexcept_t = {},
			id = {},
			int_fast16_t = {},
			int_fast8_t = {},
			ucontext_t = {},
		},
		Keyword = {
			_Nonnull = {},
			_Null_unspecified = {},
			_Nullable = {},
			__FUNCTION__ = {},
			__PRETTY_FUNCTION__ = {},
			__func__ = {},
			auto = {},
			bool = {},
			char = {},
			char16_t = {},
			char32_t = {},
			class = {},
			const = {},
			constexpr = {},
			double = {},
			enum = {},
			extern = {},
			float = {},
			int = {},
			long = {},
			operator = {},
			short = {},
			signed = {},
			static = {},
			struct = {},
			thread_local = {},
			union = {},
			unsigned = {},
			void = {},
			volatile = {},
			wchar_t = {},
		},
	},
}
