return {
	template = "\n\nfunction gp_lsp_probe() {\n  \n}",
	affixes = {
		Variable = { { prefix = "  ", suffix = ". " } },
		Field = { { prefix = "  ", suffix = "" } },
		Enum = { { prefix = "  ", suffix = "" } },
	},
	ignore = {
		Enum = {
			_VERSION = "",
		},
		Field = {
			_G = "",
			arg = "",
			coroutine = "",
			debug = "",
			io = "",
			loadfile = "",
			math = "",
			os = "",
			package = "",
			string = "",
			table = "",
			utf8 = "",
			vim = "",
		},
		Function = {
			["assert(v, message, ...)"] = "",
			["byte(s, i, j)"] = "",
			["char(byte, ...)"] = "",
			["collectgarbage(opt, ...)"] = "",
			["dofile(filename)"] = "",
			["dump(f, strip)"] = "",
			["error(message, level)"] = "",
			["find(s, pattern, init, plain)"] = "",
			["format(s, ...)"] = "",
			["getfenv(f)"] = "",
			["getmetatable(object)"] = "",
			["gmatch(s, pattern, init)"] = "",
			["gp_lsp_probe()"] = "",
			["gsub(s, pattern, repl, n)"] = "",
			["ipairs(t)"] = "",
			["len(s)"] = "",
			["load(chunk, chunkname, mode, env)"] = "",
			["loadfile(filename, mode, env)"] = "",
			["loadstring(text, chunkname)"] = "",
			["lower(s)"] = "",
			["match(s, pattern, init)"] = "",
			["module(name, ...)"] = "",
			["newproxy(proxy)"] = "",
			["next(table, index)"] = "",
			["pack(fmt, v1, v2, ...)"] = "",
			["packsize(fmt)"] = "",
			["pairs(t)"] = "",
			["pcall(f, arg1, ...)"] = "",
			["print(...)"] = "",
			["rawequal(v1, v2)"] = "",
			["rawget(table, index)"] = "",
			["rawlen(v)"] = "",
			["rawset(table, index, value)"] = "",
			["rep(s, n, sep)"] = "",
			["require(modname)"] = "",
			["reverse(s)"] = "",
			["select(index, ...)"] = "",
			["setfenv(f, table)"] = "",
			["setmetatable(table, metatable)"] = "",
			["sub(s, i, j)"] = "",
			["tonumber(e)"] = "",
			["tonumber(e, base)"] = "",
			["tostring(v)"] = "",
			["type(v)"] = "",
			["unpack(fmt, s, pos)"] = "",
			["unpack(list, i, j)"] = "",
			["upper(s)"] = "",
			["warn(message, ...)"] = "",
			["xpcall(f, msgh, arg1, ...)"] = "",
		},
		Keyword = {
			["and"] = "",
			["break"] = "",
			continue = "",
			["else"] = "",
			["end"] = "",
			["false"] = "",
			["goto"] = "",
			["local"] = "",
			["nil"] = "",
			["not"] = "",
			["or"] = "",
			["return"] = "",
			["true"] = "",
			["until"] = "",
		},
		Variable = {
			_ENV = "",
		},
	},
}
