name: docgen
on:
  push:
    branches:
      - main
      - docs
  pull_request:
    branches:
      - main
      - docs
jobs:
  docs:
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.event.pull_request.head.ref, 'release-please') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update README with Snippet Permalink
        uses: Robitx/snippet-permalink-updater-action@main
        with:
          snippet_file: 'lua/gp/config.lua'
          start_marker: 'README_REFERENCE_MARKER_START'
          end_marker: 'README_REFERENCE_MARKER_END'
          markdown_file: 'README.md'
          replace_marker: '<!-- README_REFERENCE_MARKER_REPLACE_NEXT_LINE -->'

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: gp.nvim
          version: "Neovim"
          demojify: true
          treesitter: true
          docmapping: true
          docmappingprojectname: false
          dedupsubheadings: false

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update README and auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
